import React from "react";

import MUIDataTable from "mui-datatables";


class App extends React.Component {
  render() {
    const columns =  [
      {name: "Site Number"}, 
      {name: "Site Name"}, 
      {name: "Services"}, 
      {name: "Status"},
    
    
    ];
  
    
// static data (hard coded) part of the state
    const  sitedata = [
        
["10003", "Waterford Park", "Electricity", "Lost"], 
["10005", "Manor Lakes", "Electricity", "Lost"], 
["10006", "Bedford Heights ", "Electricity", "Active"], 
["10008", "Lynbrook", "Electricity", "Lost"], 
["10010", "QV1 ", "Water", "Active"], 
["10011", "Showgrounds Village ", "Electricity", "Active"], 
["10013", "M1urban ", "Electricity", "Active"], 
["10014", "Site One ", "Electricity", "Active"], 
["10016", "Allegro ", "Electricity", "Active"], 
["10017", "12 Cato Street ", "Electricity", "Active"], 
["10018", "Esprit Apartments ", "Electricity", "Active"], 
["10019", "Lloyd Street ", "Electricity", "Active"], 
["10020", "Watergardens SC", "Electricity", "Lost"], 
["10021", "Endeavour Hills SC ", "Electricity", "Active"], 
["10022", "Stud Park SC ", "Electricity", "Active"], 
["10023", "Claremont St", "Electricity", "Lost"], 
["10024", "Travencore", "Electricity", "Lost"], 
["10025", "Claredon St ", "Electricity", "Active"], 
["10026", "Lynbrook RV", "Electricity", "Lost"], 
["10028", "109 Burwood Rd ", "Electricity", "Active"], 
["10029", "South Morang Industrial Park ", "Electricity", "Active"], 
["10030", "Marthas Point", "Electricity", "Lost"], 
["10031", "Gordon Place ", "Electricity", "Active"], 
["10032", "Albert St ", "Electricity", "Active"], 
["10034", "Victoria Square ", "Electricity", "Active"], 
["10035", "The Pines ", "Electricity", "Active"], 
["10036", "Aquavista ", "Electricity", "Active"], 
["10038", "The District Docklands ", "Electricity", "Active"], 
["10039", "Southbank One ", "Electricity, Hot Water", "Active"], 
["10040", "Cityside Apartments ", "Electricity", "Active"], 
["10041", "Eastland SC", "Electricity", "Lost"], 
["10043", "600-610 Victoria St ", "Electricity", "Active"], 
["10044", "Uni Hills Factory Outlet ", "Electricity", "Active"], 
["10045", "Cumberland Resort", "Electricity", "Lost"], 
["10047", "Benton Sq SC", "Electricity", "Lost"], 
["10048", "Yarra St ", "Electricity", "Active"], 
["10049", "QM @ Pentridge", "Electricity", "Lost"], 
["10050", "Vue Grande ", "Electricity", "Active"], 
["10051", "Waverley Gardens ", "Electricity", "Active"], 
["10051", "Waverley Gardens", "Electricity", "Lost"], 
["10052", "Moonee Ponds SC ", "Electricity", "Active"], 
["10053", "Doncaster Offices ", "Electricity", "Active"], 
["10054", "Lochmore Apartments ", "Electricity", "Active"], 
["10055", "Woodgrove SC ", "Electricity", "Active"], 
["10055", "Woodgrove SC", "Electricity", "Lost"], 
["10056", "Sunbury SC ", "Electricity", "Active"], 
["10057", "Sienna & ALT ", "Electricity", "Active"], 
["10058", "Adio Apartments ", "Electricity", "Active"], 
["10059", "672 Glenferie Rd ", "Electricity", "Active"], 
["10060", "Elvera Apartments ", "Electricity", "Active"], 
["10061", "Melbourne Airport ", "Electricity", "Active"], 
["10061", "Melbourne Airport ", "Water", "Active"], 
["10063", "Milleara SC ", "Electricity", "Active"], 
["10064", "ABecket Tower ", "Electricity", "Active"], 
["10065", "Askew House ", "Electricity", "Active"], 
["10066", "Coburg trade Centre ", "Electricity", "Active"], 
["10067", "33 W ", "Electricity", "Active"], 
["10068", "City Tempo ", "Electricity", "Active"], 
["10069", "Gisborne Village ", "Electricity", "Active"], 
["10070", "Elm Apartments ", "Electricity", "Active"], 
["10071", "77 River St ", "Electricity", "Active"], 
["10072", "Pump House ", "Electricity", "Active"], 
["10073", "Centum ", "Electricity", "Active"], 
["10074", "Toronga Village ", "Electricity", "Active"], 
["10075", "Harbour One ", "Electricity", "Active"], 
["10077", "Lilli Apartments ", "Electricity", "Active"], 
["10078", "Greensborough Plaza ", "Electricity", "Active"], 
["10079", "Westfield Doncaster", "Electricity", "Lost"], 
["10080", "Rhapsody Apartments ", "Electricity", "Active"], 
["10081", "Mayada APT ", "Electricity", "Active"], 
["10082", "Silo ", "Electricity", "Active"], 
["10083", "Dolce Apartments ", "Electricity", "Active"], 
["10084", "The Nicholson ", "Electricity", "Active"], 
["10086", "50 claremont St ", "Electricity", "Active"], 
["10087", "Richmond-A Place to Live ", "Electricity", "Active"], 
["10089", "Marina APT ", "Electricity", "Active"], 
["10090", "Lacrosse ", "Electricity", "Active"], 
["10091", "CUBO ", "Electricity", "Active"], 
["10092", "Vogue Apartments ", "Electricity", "Active"], 
["10093", "MAPLE ", "Electricity", "Active"], 
["10094", "Luna Apartments ", "Electricity", "Active"], 
["10095", "Waterside ", "Electricity", "Active"], 
["10096", "Stockland Highlands ", "Electricity", "Active"], 
["10096", "Stockland Highlands", "Electricity", "Lost"], 
["10097", "41 York Street ", "Electricity", "Active"], 
["10098", "33 M ", "Electricity", "Active"], 
["10099", "AMNE Apartments ", "Electricity", "Active"], 
["10100", "Mainpoint ", "Electricity", "Active"], 
["10101", "ROI APT ", "Electricity", "Active"], 
["10102", "Queen Victoria Market ", "Electricity", "Active"], 
["10103", "Tiara Apartments ", "Electricity", "Active"], 
["10104", "Guild Apatments ", "Electricity", "Active"], 
["10105", "Soul ", "Electricity", "Active"], 
["10106", "Otto Apartments ", "Electricity", "Active"], 
["10107", "Westfield Fountain Gate", "Electricity", "Lost"], 
["10108", "View Apartments ", "Electricity", "Active"], 
["10109", "Melbourne Market Authority ", "Electricity", "Active"], 
["10110", "Silverleaf ", "Electricity", "Active"], 
["10111", "50 Albert Road ", "Electricity", "Active"], 
["10111", "50 Albert Road", "Electricity", "Lost"], 

["10112", "Malvern Hill", "Electricity", "Lost"], 
["10113", "Eden Apartments ", "Electricity", "Active"], 
["10114", "Haven Apartments ", "Electricity", "Active"], 
["10115", "Sanctuary Apts ", "Electricity", "Active"], 
["10116", "The Gateway ", "Electricity", "Active"], 
["10118", "38 Camberwell ", "Electricity", "Active"], 
["10119", "Joulia ", "Electricity", "Active"], 
["10120", "Cavanagh ", "Electricity", "Active"], 
["10121", "Westfield Plenty Valley", "Electricity", "Lost"], 
["10122", "Lido Apartments ", "Electricity", "Active"], 
["10123", "Art in the Park ", "Electricity", "Active"], 
["10124", "Westfield Geelong", "Electricity", "Lost"], 
["10125", "Epic ", "Electricity", "Active"], 
["10126", "The Avenue ", "Electricity", "Active"], 
["10127", "52 Park St Apartments ", "Electricity", "Active"], 
["10128", "The Quay ", "Electricity", "Active"], 
["10129", "110 Trenerry Cres ", "Electricity", "Active"], 
["10130", "CIRQUE ", "Electricity", "Active"], 
["10131", "Trilogy ", "Electricity", "Active"], 
["10132", "BLISS Apartments ", "Electricity", "Active"], 
["10133", "The Guilfoyle ", "Electricity", "Active"], 
["10133", "The Guilfoyle", "Electricity", "Lost"], 
["10134", "Lantana Apartments ", "Electricity", "Active"], 
["10135", "Aura Apartments ", "Electricity", "Active"], 
["10136", "Swindon Apartments ", "Electricity", "Active"], 
["10137", "Atria Apartments ", "Electricity", "Active"], 
["10138", "Monarc Apartments ", "Electricity", "Active"], 
["10139", "My 80 Apartments ", "Electricity", "Active"], 
["10140", "Green Square ", "Electricity", "Active"], 
["10141", "Stratus Apartments ", "Electricity", "Active"], 
["10142", "IKON ", "Electricity", "Active"], 
["10143", "Maidstone ", "Electricity", "Active"], 
["10144", "568 Collins St ", "Electricity", "Active"], 
["10145", "Upper House Apartments ", "Electricity", "Active"], 
["10148", "TIVOLI Apartments ", "Electricity", "Active"], 
["10149", "Merri Parade Apartments ", "Electricity", "Active"], 
["10150", "Greville St Apartments ", "Electricity", "Active"], 
["10151", "Skyloft ", "Electricity", "Active"], 
["10152", "Trinity ", "Electricity", "Active"], 
["10152", "Trinity", "Electricity", "Lost"], 
["10153", "Flagstaff Place ", "Electricity", "Active"], 
["10154", "Westfield Knox", "Electricity", "Lost"], 
["10155", "Craigieburn Town Centre ", "Electricity", "Active"], 
["10156", "Emporia ", "Electricity", "Active"], 
["10157", "Element ", "Electricity", "Active"], 
["10158", "Riviere ", "Electricity", "Active"], 
["10159", "Bravo Apartments ", "Electricity", "Active"], 
["10160", "Oxley ", "Electricity", "Active"], 
["10161", "Alessi Apartments ", "Electricity", "Active"], 
["10162", "Audrey Apartments ", "Electricity", "Active"], 
["10163", "299 Maribyrnong Rd ", "Electricity", "Active"], 
["10164", "Scout Apartments ", "Electricity", "Active"], 
["10165", "Central Gardens ", "Electricity", "Active"], 
["10166", "Lucia APT ", "Electricity", "Active"], 
["10167", "Stockland Traralgon ", "Electricity", "Active"], 
["10168", "55 Collins St ", "Electricity", "Active"], 
["10169", "Mosiac Apts ", "Electricity", "Active"], 
["10170", "Geox Apartments ", "Electricity", "Active"], 
["10171", "Mink Apartments ", "Electricity", "Active"], 
["10172", "The Hub Richmond ", "Electricity", "Active"], 
["10173", "Stockland Wendouree Plaza ", "Electricity", "Active"], 
["10175", "Southbank Grand ", "Electricity", "Active"], 
["10176", "Swanston Square Apartments ", "Electricity", "Active"], 
["10177", "Mr Smith Apartments ", "Electricity", "Active"], 
["10178", "20 Queen Street Blackburn ", "Electricity", "Active"], 
["10179", "Featherbrook SC ", "Electricity", "Active"], 
["10180", "Momentum Apartments ", "Electricity", "Active"], 
["10181", "Orbis Apts ", "Electricity", "Active"], 
["10182", "Kubix Apts ", "Electricity", "Active"], 
["10183", "139 Chetwynd St Nth Melbourne ", "Electricity", "Active"], 
["10184", "Santorini Apartments ", "Electricity", "Active"], 
["10185", "Jika Apartments ", "Electricity", "Active"], 
["10186", "354 Barkly St Elwood Apartments ", "Electricity", "Active"], 
["10188", "EQ Tower ", "Electricity", "Active"], 
["10189", "YouandI Apts ", "Electricity", "Active"], 
["10190", "2 Tube St ", "Electricity", "Active"], 
["10191", "Solstice Apartments ", "Electricity", "Active"], 
["10191", "Solstice Apartments ", "Hot Water", "Active"], 
["10193", "Yarra House ", "Electricity", "Active"], 
["10194", "C3 Apartments ", "Electricity", "Active"], 
["10194", "C3 Apartments ", "Hot Water", "Active"], 
["10195", "North Apartments ", "Electricity", "Active"], 
["10195", "North Apartments ", "Hot Water", "Active"], 
["10196", "Leroy Apartments ", "Electricity", "Active"], 
["10197", "Canopy Apartments ", "Electricity", "Active"], 
["10198", "381 Cremorne ", "Electricity", "Active"], 
["10198", "381 Cremorne", "Electricity", "Lost"], 
["10199", "Parkwood APT ", "Electricity", "Active"], 
["10199", "Parkwood Apartments ", "Hot Water", "Active"], 
["10200", "Botanica ", "Electricity", "Active"], 
["10200", "Botanica ", "Hot Water", "Active"], 
["10201", "Banque 88 ", "Electricity", "Active"], 
["10202", "The Chapters Uni Hill Apartments ", "Electricity", "Active"], 
["10203", "Melbourne One ", "Electricity", "Active"], 
["10204", "Bouverie Street ", "Electricity, Hot Water, Fair Air", "Active"], 
["10205", "Oscar Apartments ", "Electricity", "Active"], 
["10205", "Oscar Apartments ", "Hot Water", "Active"], 
["10206", "QMA Apartments ", "Electricity", "Active"], 
["10206", "QMA Apartments", "Electricity", "Lost"], 
["10207", "The Archer 1-9 Balcombe Rd ", "Electricity", "Active"], 
["10208", "Murphy St ", "Electricity", "Active"], 
["10209", "Arcadia Apartments ", "Electricity", "Active"], 
["10210", "Play House Apartments ", "Electricity", "Active"], 
["10211", "Ikebana Apartment", "Electricity", "Active"], 
["10212", "George Windsor ", "Electricity", "Active"], 
["10214", "Australis ", "Electricity", "Active"], 
["10215", "Decco Apartments ", "Electricity", "Active"], 
["10216", "Vision Apartments ", "Electricity", "Active"], 
["10218", "420 Spencer Street ", "Electricity", "Active"], 
["10218", "420 Spencer Street ", "Hot Water", "Active"], 
["10219", "Britannia Rise ", "Electricity", "Active"], 
["10219", "Britannia Rise ", "Hot Water", "Active"], 
["10220", "Doncaster Townhouses ", "Electricity", "Active"], 
["10221", "Verdis Apartments ", "Electricity", "Active"], 
["10222", "The York Brunswick ", "Electricity", "Active"], 
["10223", "The Lantern ", "Electricity", "Active"], 
["10223", "The Lantern ", "Hot Water", "Active"], 
["10224", "A Albert ", "Electricity", "Active"], 
["10226", "The Hub Hamilton ", "Electricity", "Active"], 
["10227", "Jewel Apartments ", "Electricity", "Active"], 
["10228", "Ruba Apartments ", "Electricity", "Active"], 
["10229", "Saint Martin ", "Electricity", "Active"], 
["10229", "Saint Martin ", "Hot Water", "Active"], 
["10230", "Elsternwick Place Apartments ", "Electricity", "Active"], 
["10230", "Elsternwick Place Apartments ", "Hot Water", "Active"], 
["10231", "Northwood Apartments ", "Electricity", "Active"], 
["10232", "Whitehorse Towers ", "Electricity", "Active"], 
["10232", "Whitehorse Towers ", "Hot Water", "Active"], 
["10233", "Banbury Village ", "Electricity", "Active"], 
["10233", "Banbury Village ", "Hot Water", "Active"], 
["10234", "107 Cambridge ", "Electricity", "Active"], 
["10234", "107 Cambridge ", "Hot Water", "Active"], 
["10235", "Empire Apartments ", "Electricity", "Active"], 
["10235", "Empire Apartments ", "Hot Water", "Active"], 
["10236", "Gravity ", "Electricity", "Active"], 
["10236", "Gravity ", "Hot Water", "Active"], 
["10239", "Southbank Central ", "Electricity", "Active"], 
["10239", "Southbank Central ", "Hot Water", "Active"], 
["10240", "Parque Apartments ", "Electricity", "Active"], 
["10240", "Parque Apartments ", "Hot Water", "Active"], 
["10241", "Ingles St ", "Electricity", "Active"], 
["10242", "Rima ", "Electricity", "Active"], 
["10242", "Rima ", "Hot Water", "Active"], 
["10243", "MDocklands ", "Electricity", "Active"], 
["10244", "Queens Domain ", "Electricity", "Active"], 
["10244", "Queens Domain ", "Hot Water", "Active"], 
["10245", "Orr Apartments ", "Electricity", "Active"], 
["10246", "MV1 ", "Electricity", "Active"], 
["10247", "Middle Burke ", "Electricity", "Active"], 
["10247", "Middle Burke ", "Hot Water", "Active"], 
["10248", "Lakeside Apartments ", "Electricity", "Active"], 
["10248", "Lakeside Apartments ", "Hot Water", "Active"], 
["10250", "Essence ", "Electricity", "Active"], 
["10250", "Essence ", "Hot Water", "Active"], 
["10251", "Willows Apartment ", "Electricity", "Active"], 
["10251", "Willows Apartment ", "Hot Water", "Active"], 
["10252", "Garden Hill ", "Electricity", "Active"], 
["10252", "Garden Hill ", "Hot Water", "Active"], 
["10253", "International Melbourne ", "Electricity", "Active"], 
["10253", "International Melbourne ", "Hot Water", "Active"], 
["10254", "Buckley Apartments ", "Electricity", "Active"], 
["10254", "Buckley Apartments ", "Hot Water", "Active"], 
["10255", "Noir ", "Electricity", "Active"], 
["10255", "Noir ", "Hot Water", "Active"], 
["10256", "Aurora ", "Electricity", "Active"], 
["10257", "Conservatory ", "Electricity", "Active"], 
["10258", "Regent ", "Electricity", "Active"], 
["10259", "Stanley St ", "Electricity", "Active"], 
["10259", "Stanley St ", "Hot Water", "Active"], 
["10260", "Southbank Place ", "Electricity", "Active"], 
["10260", "Southbank Place ", "Hot Water", "Active"], 
["10261", "Vanguard ", "Electricity", "Active"], 
["10261", "Vanguard ", "Hot Water", "Active"], 
["10263", "Riverside ", "Electricity", "Active"], 
["10263", "Riverside ", "Hot Water", "Active"], 
["10264", "Gardenhurst ", "Electricity", "Active"], 
["10264", "Gardenhurst ", "Hot Water", "Active"], 
["10265", "Richmond Place ", "Electricity", "Active"], 
["10265", "Richmond Place ", "Hot Water", "Active"], 
["10266", "Nest at the Hill ", "Electricity", "Active"], 
["10266", "Nest at the Hill ", "Hot Water", "Active"], 
["10267", "Royal Como ", "Electricity", "Active"], 
["10267", "Royal Como ", "Hot Water", "Active"], 
["10268", "881 Armadale ", "Electricity", "Active"], 
["10268", "881 Armadale ", "Hot Water", "Active"], 
["10269", "Union Tower ", "Electricity", "Active"], 
["10269", "Union Tower ", "Hot Water", "Active"], 
["10270", "Carrington ", "Electricity", "Active"], 
["10270", "Carrington ", "Hot Water", "Active"], 
["10271", "19 Coporate Dr ", "Electricity", "Active"], 
["10272", "Kings Domain ", "Electricity", "Active"], 
["10272", "Kings Domain ", "Hot Water", "Active"], 
["10273", "Portrait Apartments ", "Electricity", "Active"], 
["10273", "Portrait Apartments ", "Hot Water", "Active"], 
["10274", "Wattle Apartments ", "Electricity", "Active"], 
["10274", "Wattle Apartments ", "Hot Water", "Active"], 
["10275", "Summus ", "Electricity", "Active"], 
["10275", "Summus ", "Hot Water", "Active"], 
["10278", "1027800 - Vescada ", "Electricity", "Active"], 
["10278", "Vescada ", "Hot Water", "Active"], 
["10279", "Aerocorp Business Park ", "Electricity", "Active"], 
["10282", "Valley Private Hospital ", "Electricity", "Active"], 
["10286", "1028600 - Arden Gardens ", "Electricity", "Active"], 
["10286", "Arden Gardens ", "Hot Water", "Active"], 
["10288", "Capitol Grand ", "Electricity", "Active"], 
["10288", "Capitol Grand ", "Hot Water", "Active"], 
["10296", "Morris Moor ", "Electricity", "Active"], 
["10298", "140 William ", "Electricity", "Active"], 
["20001", "Broadway SC ", "Electricity", "Active"], 
["20002", "Rhodes ", "Electricity", "Active"], 
["20003", "Westpoint SC ", "Electricity", "Active"], 
["20003", "Westpoint SC", "Electricity", "Lost"], 
["20004", "Westfield Sydney City", "Electricity", "Lost"], 
["20005", "Gowrie St Mall ", "Electricity", "Active"], 
["20005", "Gowrie St Mall", "Electricity", "Lost"], 
["20006", "Westfield Hornsby", "Electricity", "Lost"], 
["20007", "Gladstone Ave Wollongong ", "Electricity", "Active"], 
["20008", "Silver Square ", "Electricity", "Active"], 
["20009", "Astral Apartments ", "Electricity", "Active"], 
["20010", "Riviera Apartments ", "Electricity", "Active"], 
["20011", "42 Pemberton St ", "Electricity", "Active"], 
["20012", "Westfield Miranda", "Electricity", "Lost"], 
["20013", "Platinum ", "Electricity", "Active"], 
["20014", "Eclipse ", "Electricity", "Active"], 
["20015", "Eleebana Res ", "Electricity", "Active"], 
["20016", "East Village Residential ", "Electricity", "Active"], 
["20017", "East Village Victoria Park ", "Electricity", "Active"], 
["20017", "East Village Victoria Park ", "CHW & HHW", "Active"], 
["20018", "Bridgehill Residences ", "Electricity", "Active"], 
["20019", "Aspect ", "Electricity", "Active"], 
["20020", "Haran Street ", "Electricity", "Active"], 
["20021", "Rise Apartment ", "Electricity", "Active"], 
["20022", "Waratah Building D ", "Electricity", "Active"], 
["20023", "Chatswood Transport Interchange ", "Electricity", "Active"], 
["20024", "Stockland Merrylands ", "Electricity", "Active"], 
["20024", "Stockland Merrylands NUoS ", "Electricity", "Active"], 
["20025", "Stockland Shellharbour ", "Electricity", "Active"], 
["20025", "Stockland Shellharbour NUoS ", "Electricity", "Active"], 
["20026", "Glenhaven Living Choice", "Electricity", "Lost"], 
["20027", "Vicinity Apartment ", "Electricity", "Active"], 
["20028", "Roseberry Apartments ", "Electricity", "Active"], 
["20029", "Shepherds Bay - Oxford ", "Electricity", "Active"], 
["20030", "Como - Stage 1 ", "Electricity", "Active"], 
["20031", "Fairmount - Stage 1 ", "Electricity", "Active"], 
["20032", "55 Coonara Ave ", "Electricity", "Active"], 
["20033", "Arise Apartments ", "Electricity", "Active"], 
["20033", "Arise Apartments ", "Hot Water", "Active"], 
["20035", "Atmosphere ", "Electricity", "Active"], 
["20035", "Atmosphere NSW ", "Hot Water", "Active"], 
["20036", "Lindfield Apartment ", "Electricity", "Active"], 
["20037", "Garden Village ", "Electricity", "Active"], 
["20038", "Eve Apartment ", "Electricity", "Active"], 
["20039", "Skyhaus Apartment ", "Electricity", "Active"], 
["20040", "Infinity Merrylands", " Electricity", "Active"], 
["20040", "Infinity Merrylands ", "Hot Water", "Active"], 
["20041", "Wings Apartments ", "Electricity", "Active"], 
["20042", "The Belle Apartments ", "Electricity", "Active"], 
["20042", "The Belle Apartments ", "Hot Water", "Active"], 
["20043", "Westmead Private Hospital ", "Electricity", "Active"], 
["20044", "Capitol Bondi APT", "Electricity", "Active"], 
["20045", "Meriton Chatswood ", "Electricity", "Active"], 
["20046", "Arena Apartment ", "Electricity", "Active"], 
["20047", "Zeta Apartment ", "Electricity", "Active"], 
["20047", "Zeta Apartment ", "Hot Water", "Active"], 
["20049", "Luna Apartments NSW ", "Electricity", "Active"], 
["20049", "Luna Apartments NSW ", "Hot Water", "Active"], 
["20050", "Meriton Mascot ", "Electricity", "Active"], 
["20052", "Crimson Hill APT ", "Electricity", "Active"], 
["20053", "Devcon Penrith ", "Electricity", "Active"], 
["20054", "Northgate APT ", "Electricity", "Active"], 
["20055", "Croft Apartment ", "Electricity", "Active"], 
["20056", "The Crown Apartments ", "Electricity", "Active"], 
["20058", "Bosco Apartments ", "Electricity", "Active"], 
["20059", "Flour Mill ", "Electricity", "Active"], 
["20062", "Holdmark Majors Bay ", "Electricity", "Active"], 
["20075", "Habitat Apartments ", "Electricity", "Active"], 
["20075", "Habitat Apartments ", "Hot Water", "Active"], 
["20077", "Macquarie Towers ", "Electricity", "Active"], 
["20080", "Parklands Hillsdale ", "Electricity", "Active"], 
["20080", "Parklands Hillsdale ", "Hot Water", "Active"], 
["20084", "Overland Garden Bld B-C ", "Electricity", "Active"], 
["20084", "overland Garden Bld B-C ", "Hot Water", "Active"], 
["20085", "Overland Garden Bld E-F", "Electricity", "Active"], 
["20087", "Bathers Kiama NSW ", "Electricity", "Active"], 
["20087", "Bathers Kiama NSW ", "Hot Water", "Active"], 
["20087", "Bathers Kiama NSW ", "Gas", "Active"], 
["20088", "Oceana Apartments ", "Electricity", "Active"], 
["20089", "Bankstown Apartments ", "Electricity", "Active"], 
["20090", "Element IQ ", "Electricity", "Active"], 
["20091", "Spire Apartment ", "Electricity, Hot Water", "Active"], 
["20092", "Peony Place ", "Electricity", "Active"], 
["20092", "Peony Place ", "Hot Water", "Active"], 
["20093", "Wolli Creek Apt ", "Electricity", "Active"], 
["20093", "Wolli Creek Apt ", "Hot Water", "Active"], 
["20094", "Esprit NSW Apartment ", "Electricity", "Active"], 
["20094", "Esprit NSW Apartment ", "Hot Water", "Active"], 
["20095", "Woolooware Bay ", "Electricity", "Active"], 
["20096", "Rouse Hill APT ", "Electricity", "Active"], 
["20097", "Paragon Zetland ", "Electricity", "Active"], 
["20098", "The Huxley ", "Electricity", "Active"], 
["20098", "The Huxley ", "Hot Water", "Active"], 
["20099", "Westend Apartments ", "Electricity", "Active"], 
["20099", "Westend Apartments ", "Hot Water", "Active"], 
["20100", "88 Kensington ", "Electricity", "Active"], 
["20100", "88 Kensington ", "Hot Water", "Active"], 
["20100", "88 Kensington ", "Gas", "Active"], 
["20101", "Time and Place ", "Electricity", "Active"], 
["20101", "Time and Place ", "Hot Water", "Active"], 
["20102", "Luxe Eve Apartment ", "Electricity", "Active"], 
["20103", "The Grange - Lifestyle Village ", "Electricity", "Active"], 
["20106", "Stockland Green Hills ", "Electricity", "Active"], 
["20107", "AMP Macquarie Centre ", "Electricity", "Active"], 
["20108", "Top Garden ", "Hot Water", "Active"], 
["20108", "Top Garden ", "Electricity", "Active"], 
["20109", "Visum APT NSW ", "Hot Water", "Active"], 
["20109", "Visum APT NSW ", "Electricity", "Active"], 
["20110", "Mint - The Gallery NSW ", "Hot Water", "Active"], 
["20110", "Mint - The Gallery NSW ", "Electricity", "Active"], 
["20111", "The Harts Landing ", "Electricity", "Active"], 
["20113", "Glenmore Park SC ", "Electricity", "Active"], 
["20114", "Jewel Residencies ", "Electricity", "Active"], 
["20122", "Aveo Norwest ", "Electricity", "Active"], 
["20122", "Aveo Norwest ", "Hot Water", "Active"], 
["20122", "Aveo Norwest ", "GAS", "Active"], 
["20123", "Ventus Blacktown NSW ", "Hot Water", "Active"], 
["20123", "Ventus Blacktown NSW ", "Electricity", "Active"], 
["20123", "Ventus Blacktown NSW ", "GAS", "Active"], 
["20125", "Weston APT NSW ", "Hot Water", "Active"], 
["20125", "Weston APT NSW ", "Electricity", "Active"], 
["20126", "No 1 Carlingford NSW ", "Electricity", "Active"], 
["20128", "The Adeline NSW ", "Electricity", "Active"], 
["20134", "Woolooware Stage 2 ", "Electricity", "Active"], 
["20134", "Woolooware Stage 2 ", "Hot Water", "Active"], 
["20138", "Woolooware Stage 3 ", "Electricity", "Active"], 
["20138", "Woolooware Stage 3 ", "Hot Water", "Active"], 
["20142", "The Atrium NSW ", "Electricity", "Active"], 
["20145", "South Village NSW ", "Electricity", "Active"], 
["30003", "Waterford Court ", "Electricity", "Active"], 
["30004", "Vida Apartments ", "Electricity", "Active"], 
["30005", "Halpine Central ", "Electricity", "Active"], 
["30006", "Spire ", "Electricity", "Active"], 
["30006", "Spire ", "Hot Water", "Active"], 
["30006", "Spire ", "Fair Air", "Active"], 
["30007", "Cornerstone Living ", "Electricity", "Active"], 
["30007", "Cornerstone Living ", "Hot Water", "Active"], 
["30008", "The Johnson ", "Electricity", "Active"], 
["30008", "The Johnson ", "Hot Water", "Active"], 
["30009", "Magnus ", "Electricity", "Active"], 
["30009", "Magnus ", "Hot Water", "Active"], 
["30009", "Magnus Apartments ", "Gas", "Active"], 
["30011", "The Mall Beenleigh ", "Electricity", "Active"], 
["30012", "Parkside ", "Electricity", "Active"], 
["30013", "FV Apartments ", "Electricity", "Active"], 
["30013", "FV Apartments ", "Hot Water", "Active"], 
["30016", "Cornerstone Living Stage D ", "Electricity", "Active"], 
["30016", "Cornerstone Living Stage D ", "Hot Water", "Active"], 
["30020", "Cornerstone Living Stage I ", "Electricity", "Active"], 
["30020", "Cornerstone Living Stage 1 ", "Hot Water", "Active"], 
["30022", "Cornerstone Living Stage K ", "Electricity", "Active"], 
["30033", "West Village Buildings 1 and 2 ", "Electricity", "Active"], 
["30033", "West Village Buildings 1 and 2 ", "Hot Water", "Active"], 
["30034", "The Winn ", "Electricity", "Active"], 
["30034", "The Winn ", "Hot Water", "Active"], 
["30035", "Marina Concourse ", "Electricity", "Active"], 
["30035", "Marina Concourse ", "Hot Water", "Active"], 
["30036", "344 Bilsen Rd ", "Electricity", "Active"], 
["30037", "Summerlin ", "Electricity", "Active"], 
["30038", "Aveo Springfield ", "Electricity", "Active"], 
["30038", "Aveo Springfield ", "Hot Water", "Active"], 
["30039", "The Wellington ", "Electricity", "Active"], 
["30039", "The Wellington ", "Hot Water", "Active"], 
["30041", "Willows SC ", "Electricity", "Active"], 
["30042", "Aveo Newstead ", "Electricity", "Active"], 
["30042", "Aveo Newstead ", "Hot Water", "Active"], 
["30043", "Smithfield SC ", "Electricity", "Active"], 
["30044", "Pavilions on Parkvue ", "Electricity", "Active"], 
["30045", "Aveo Robertson Park ", "Electricity", "Active"], 
["30045", "Aveo Robertson Park ", "Hot Water", "Active"], 
["30046", "Beenleigh Marketplace ", "Electricity", "Active"], 
["30048", "Coomera City Centre ", "Electricity", "Active"], 
["30053", "Ripley Town Centre ", "Electricity", "Active"], 
["40001", "Vue Apartments ", "Electricity", "Active"], 
["40001", "VUE Apartment ", "Hot Water", "Active"], 
["40001", "Vue Apartment ", "Gas", "Active"], 
["40002", "Bohem Apartments ", "Electricity", "Active"], 
["40002", "Bohem Apartments ", "Hot Water", "Active"], 
["40002", "Bohem Apartments ", "Gas", "Active"], 
["40003", "Brickworks Marketplace ", "Electricity", "Active"], 
["40004", "West Franklin Apartments ", "Electricity", "Active"], 
["50001", "Banksia Grove Village SC - Coles ", "Electricity", "Active"], 
["50002", "Byford Village ", "Electricity", "Active"], 
["50003", "Lakelands SC ", "Electricity", "Active"], 
["99999", "WINAUSPOWER ", "Retail", "Active"]

    ];
// page settings (number of rows, scroll, options in general) part of the state
    const options = {
      filterType: "dropdown",
      rowsPerPage: 5,
      page: 0,
      responsive: "scroll",
      viewColumns: false,
      print: false,
      orderby: 'Site Number',
      rowsPerPageOptions: [5, 10, 15, 25, 50, 100],
      selectableRows: false,
      sort: true,
      fixedHeader: false,
   // download: false,
      serverSide : false,
      width: 35
    };

    

    return (
      <MUIDataTable
        title={"Site Management"}
        data={sitedata}
        columns={columns}
        options={options}
        
      />
    );
  }
}
export default App